In [1]:
import pandas as pd

In [2]:
mower=pd.read_csv(mower_market_snapshot.csv)

NameError: name 'mower_market_snapshot' is not defined

In [4]:
mower=pd.read_csv('mower_market_snapshot.csv')

In [5]:
mower.head

<bound method NDFrame.head of      capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0     10.492623311991721;0.04252798088681092;18377;6...
1     20.273730444538863;0.037896368225955296;19363;...
2     20.19045691648912;0.039111245954194296;19641;7...
3     27.220131037450034;0.04130311679867133;18728;6...
4     16.370911056135107;0.037938171867880455;18722;...
...                                                 ...
1394  44.959894548992835;0.2346469274422487;18451;63...
1395  59.35605810795307;0.253693682727865;18663;64.0...
1396  67.86522214290575;0.22893453099780575;19169;62...
1397  66.85543549976667;0.24494793928030933;18946;58...
1398  54.71271281827748;0.17714343396168158;19017;64...

[1399 rows x 1 columns]>

In [6]:
mower.head(5)

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [7]:
df = pd.read_csv('mower_market_snapshot.csv')

In [8]:
df

     capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0     10.492623311991721;0.04252798088681092;18377;6...
1     20.273730444538863;0.037896368225955296;19363;...
2     20.19045691648912;0.039111245954194296;19641;7...
3     27.220131037450034;0.04130311679867133;18728;6...
4     16.370911056135107;0.037938171867880455;18722;...
...                                                 ...
1394  44.959894548992835;0.2346469274422487;18451;63...
1395  59.35605810795307;0.253693682727865;18663;64.0...
1396  67.86522214290575;0.22893453099780575;19169;62...
1397  66.85543549976667;0.24494793928030933;18946;58...
1398  54.71271281827748;0.17714343396168158;19017;64...

[1399 rows x 1 columns]

In [9]:
mower.head(5)

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [10]:
mower=pd.read_csv('mower_market_snapshot.csv')
mower

     capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0     10.492623311991721;0.04252798088681092;18377;6...
1     20.273730444538863;0.037896368225955296;19363;...
2     20.19045691648912;0.039111245954194296;19641;7...
3     27.220131037450034;0.04130311679867133;18728;6...
4     16.370911056135107;0.037938171867880455;18722;...
...                                                 ...
1394  44.959894548992835;0.2346469274422487;18451;63...
1395  59.35605810795307;0.253693682727865;18663;64.0...
1396  67.86522214290575;0.22893453099780575;19169;62...
1397  66.85543549976667;0.24494793928030933;18946;58...
1398  54.71271281827748;0.17714343396168158;19017;64...

[1399 rows x 1 columns]

In [11]:
df = pd.read_csv('mower_market_snapshot.csv')
df

     capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0     10.492623311991721;0.04252798088681092;18377;6...
1     20.273730444538863;0.037896368225955296;19363;...
2     20.19045691648912;0.039111245954194296;19641;7...
3     27.220131037450034;0.04130311679867133;18728;6...
4     16.370911056135107;0.037938171867880455;18722;...
...                                                 ...
1394  44.959894548992835;0.2346469274422487;18451;63...
1395  59.35605810795307;0.253693682727865;18663;64.0...
1396  67.86522214290575;0.22893453099780575;19169;62...
1397  66.85543549976667;0.24494793928030933;18946;58...
1398  54.71271281827748;0.17714343396168158;19017;64...

[1399 rows x 1 columns]

In [13]:
pd.set_option('display.max_columns', None)
mower.head()

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [14]:
df = pd.read_csv('mower_market_snapshot.csv')

In [15]:
df

     capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0     10.492623311991721;0.04252798088681092;18377;6...
1     20.273730444538863;0.037896368225955296;19363;...
2     20.19045691648912;0.039111245954194296;19641;7...
3     27.220131037450034;0.04130311679867133;18728;6...
4     16.370911056135107;0.037938171867880455;18722;...
...                                                 ...
1394  44.959894548992835;0.2346469274422487;18451;63...
1395  59.35605810795307;0.253693682727865;18663;64.0...
1396  67.86522214290575;0.22893453099780575;19169;62...
1397  66.85543549976667;0.24494793928030933;18946;58...
1398  54.71271281827748;0.17714343396168158;19017;64...

[1399 rows x 1 columns]

In [16]:
df.head()

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [17]:
df.tail(1)

     capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
1398  54.71271281827748;0.17714343396168158;19017;64...

In [18]:
df.describe()

       capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
count                                                1399
unique                                               1399
top     64.53614110367802;0.19884211050232437;18685;63...
freq                                                    1

In [19]:
df.iloc[: 5 ,: 10 ]

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [20]:
mower=pd.read_csv('mower_market_snapshot.csv')

In [21]:
mower.head()

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [23]:
pd.read_csv('mower_market_snapshot.csv', sep='|', header=None)

                                                      0
0     capacity;failure_rate;id;margin;price;prod_cos...
1     10.492623311991721;0.04252798088681092;18377;6...
2     20.273730444538863;0.037896368225955296;19363;...
3     20.19045691648912;0.039111245954194296;19641;7...
4     27.220131037450034;0.04130311679867133;18728;6...
...                                                 ...
1395  44.959894548992835;0.2346469274422487;18451;63...
1396  59.35605810795307;0.253693682727865;18663;64.0...
1397  67.86522214290575;0.22893453099780575;19169;62...
1398  66.85543549976667;0.24494793928030933;18946;58...
1399  54.71271281827748;0.17714343396168158;19017;64...

[1400 rows x 1 columns]

In [24]:
mower=pd.read_csv('mower_market_snapshot.csv')

In [25]:
mower.head()

  capacity;failure_rate;id;margin;price;prod_cost;product_type;quality;warranty;market_share;attractiveness
0  10.492623311991721;0.04252798088681092;18377;6...
1  20.273730444538863;0.037896368225955296;19363;...
2  20.19045691648912;0.039111245954194296;19641;7...
3  27.220131037450034;0.04130311679867133;18728;6...
4  16.370911056135107;0.037938171867880455;18722;...

In [33]:
mower=pd.read_csv('mower_market_snapshot.csv',sep=';')

In [34]:
mower.head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614

In [30]:
mower=pd.read_csv('mower_market_snapshot.csv', delimiter=';' ,sep='|')

In [31]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [32]:
mower.sort_values(by='capacity', ascending=False).head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
808,104.614865,0.196455,18966,65.249862,77.462485,12.212623662295835,essence,Low,1an,0.001265,0.667658
818,95.100035,0.232960,18476,61.929406,72.046755,10.117349820466503,essence,Low,1_an.,0.001598,0.842908
1364,94.190711,0.226721,19348,65.009978,75.624378,10.614399621337961,essence,Low,1_an.,0.001289,0.679838
709,93.720276,0.232029,19358,61.283924,72.558648,11.27472426970402,essence,Low,1an,0.001398,0.737814
833,90.847604,0.225507,18615,68.655024,80.367723,11.71269876470713,essence,Hight,1_an.,0.001280,0.675588

In [35]:
market.groupby("warranty").sum

NameError: name 'market' is not defined

In [36]:
mower.groupby("price").sum()

,capacity,failure_rate,id,margin,market_share,attractiveness
price,,,,,,
62.162200,43.410781,0.089094,19576,286.579692,0.002389,0.622614
62.855737,50.843741,0.195125,18366,53.272369,0.001364,0.719494
63.692980,63.785109,0.228977,18315,55.156346,0.001374,0.724895
63.984195,55.682973,0.219791,18808,53.612922,0.001545,0.815051
64.146445,49.237933,0.232052,18290,55.214844,0.001269,0.669645
...,...,...,...,...,...,...
935.661633,16.927674,0.035968,18726,790.012898,0.008935,0.914049
939.299327,22.045226,0.035835,19053,742.033486,0.007093,0.725596
940.317544,21.684448,0.037558,19374,775.839643,0.007962,0.814550
945.613811,25.955808,0.042562,19353,751.401681,0.005786,0.591881
964.973926,28.732437,0.031813,19031,781.467462,0.008001,0.818482

In [37]:
mower.groupby("price").mean()

,capacity,failure_rate,id,margin,market_share,attractiveness
price,,,,,,
62.162200,43.410781,0.089094,19576,286.579692,0.002389,0.622614
62.855737,50.843741,0.195125,18366,53.272369,0.001364,0.719494
63.692980,63.785109,0.228977,18315,55.156346,0.001374,0.724895
63.984195,55.682973,0.219791,18808,53.612922,0.001545,0.815051
64.146445,49.237933,0.232052,18290,55.214844,0.001269,0.669645
...,...,...,...,...,...,...
935.661633,16.927674,0.035968,18726,790.012898,0.008935,0.914049
939.299327,22.045226,0.035835,19053,742.033486,0.007093,0.725596
940.317544,21.684448,0.037558,19374,775.839643,0.007962,0.814550
945.613811,25.955808,0.042562,19353,751.401681,0.005786,0.591881
964.973926,28.732437,0.031813,19031,781.467462,0.008001,0.818482

In [41]:
df1 = pd.DataFrame({'capacity': [104.614865, 50.843741], 'price': [77.462485, 80.367723]})
df2 = pd.DataFrame({'capacity': [21.684448, 63.785109], 'price': [72.558648, 75.624378]})

In [42]:
pd.concat([df1, df2])

     capacity      price
0  104.614865  77.462485
1   50.843741  80.367723
0   21.684448  72.558648
1   63.785109  75.624378

In [43]:
mower=pd.read_csv('mower_market_snapshot.csv', delimiter=';')

In [44]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [45]:
mower.isnull().tail()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
1394,False,False,False,False,False,False,False,False,False,False,False
1395,False,False,False,False,False,False,False,False,False,False,False
1396,False,False,False,False,False,False,False,False,False,False,False
1397,False,False,False,False,False,False,False,False,False,False,False
1398,False,False,False,False,False,False,False,False,False,False,False

In [46]:
mower.notnull().tail()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
1394,True,True,True,True,True,True,True,True,True,True,True
1395,True,True,True,True,True,True,True,True,True,True,True
1396,True,True,True,True,True,True,True,True,True,True,True
1397,True,True,True,True,True,True,True,True,True,True,True
1398,True,True,True,True,True,True,True,True,True,True,True

In [47]:
mower.tail()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

# 3) 4) Analyse le nombre de valeurs manquantes standard par colonnes

In [49]:
mower.isnull().sum()

capacity           0
failure_rate       0
id                 0
margin             0
price              0
prod_cost         18
product_type       0
quality            0
warranty           0
market_share       0
attractiveness     0
dtype: int64

In [51]:
mower.isnull().sum().sum()

18

#La colonne prod_cost possede aussi des valeurs non manquantes comme : unknown, -64, 0

In [54]:
missing_values = ['unknown', '-64', '0']
mower=pd.read_csv('mower_market_snapshot.csv', delimiter=';', na_values=missing_values)

In [55]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.035519,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.318099,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.137319,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.829462,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.486938,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380589,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,NaN,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794197,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216,essence,Low,1an.,0.001022,0.538969

In [56]:
mower.isnull().sum().sum()

69

Nous obtenons 69 en ajoutant les valeurs non dÃ©fini comme : unknown, -64, 0

# 5) On remplace les valeurs manquantes par la moyenne de la colonne

In [67]:
mean = mower['prod_cost'].mean()
mower['prod_cost'].fillna(mean)

0       195.035519
1       151.318099
2       178.137319
3       162.829462
4       141.486938
           ...
1394     11.498540
1395     11.380589
1396     57.884239
1397      9.794197
1398     10.696216
Name: prod_cost, Length: 1399, dtype: float64

In [70]:
for i in mower.loc[:, "prod_cost"]:
print(i)

195.035519282118
151.31809934886763
178.13731921134948
162.82946157588628
141.48693796090603
177.01288573033196
173.26373572791334
184.56014118975136
170.14746134881673
186.1262903279073
148.41503918168814
195.81946333014687
170.99957332823436
139.9698450224172
164.85980921486097
208.752892061292
167.18992276086493
161.26365131854843
184.97391331970988
156.25068438864682
158.91492725312412
185.56823156025672
184.94371512383591
199.8793048937394
161.1003672316781
149.78979724770687
144.6246131371376
148.98982075813146
167.1419253018245
183.5064637124297
162.24738769188284
192.43158866163057
210.98494137927483
157.84556070034944
162.06122034931462
187.72517747975849
154.37302869548267
156.59559325014203
162.35254312665342
166.9972836639568
140.2610402168683
138.32693813663494
206.7959162257041
145.10773620187885
155.80155621563117
156.67297253117556
150.24402476593957
57.88423935652551
177.82356403327117
196.0274552659416
184.5971619154037
161.77140433684315
145.64873537795023
188.4054440270436
124.6385019791903
197.26584022760127
197.4016973985536
162.44278708839065
147.65232886365732
161.23832883669454
187.34829803517863
164.47790102706762
57.88423935652551
190.4235470208539
57.88423935652551
150.93607911880156
199.0423799596365
155.43790628122358
210.1386117598448
199.95563561475387
162.3670726823853
172.94399844867755
157.58631356587068
178.11211375764907
190.0213297372845
183.1284837009776
170.5749256926408
180.09183585849215
153.52008661923014
178.23271413841522
187.50039109334472
154.8314225450659
178.75604704059796
171.63063647283755
159.29147696178106
179.63947755602535
170.4020115316374
188.0197682316963
158.89661748128475
189.18150589220747
194.21213040016409
151.3829501074397
199.88503325299047
151.45651006406848
181.60273791977545
177.44454657647597
184.5701617824148
151.25346278932642
195.7674671167792
159.41950797205132
57.88423935652551
171.14471481439216
150.33198853274945
57.88423935652551
172.2127601659883
190.60368020752847
161.74528295167684
57.88423935652551
108.83102603827136
173.98329029794488
191.60107832712475
180.44742628067215
151.79048181434914
129.40055113627778
165.16168485082014
178.75083919389533
209.91165657914487
192.9995451131534
178.29518998424712
200.71689790045968
167.63119044856666
159.98895016595586
168.40341314583495
129.8468804253563
161.54826823781949
156.4747262502635
57.88423935652551
179.81628514606857
169.65699352090903
154.06974619900987
155.8356814462169
174.01893753147368
174.60956677839036
183.67864931882792
181.7952633524461
57.88423935652551
182.39311954134632
137.41445479760046
163.6768160765784
154.38621135848757
168.49669540529064
175.1443538538103
102.99756784515532
108.17064902568966
116.78270498219176
100.93962262740231
135.056982528663
110.65125973171236
115.57569098132524
87.80471659131098
85.99487906022657
126.04026925777649
122.80667070788924
119.52321476121092
57.88423935652551
136.37473754676466
122.86681486041888
93.81300605127096
119.66030242214958
110.56913820956314
106.51274187687147
131.4758159431955
57.88423935652551
88.31736106911566
106.63059385827368
105.4779946382461
57.88423935652551
120.49176952961106
112.67526219329102
110.64376375592664
57.88423935652551
111.98854473190144
116.5268597919788
119.01708516943084
130.77858949655135
97.60760688521292
117.61672269580792
111.3860139145618
98.20976606672536
141.93053446286157
125.88802853891964
127.57589422904356
142.25865713464708
96.87285950100367
94.56770375345084
57.88423935652551
128.0125685973065
131.53030953901532
114.05099998479103
124.1535861743869
119.29034837314454
103.17336718648698
107.75850187808685
119.22207921356276
137.96846397787198
96.34028375521208
148.0169214755135
101.74953065482592
119.75127733368872
131.7668579105174
113.61220560465058
110.81031330760976
102.79066578483608
115.77213490280354
57.88423935652551
121.3167171267889
132.84807351140307
122.26118459128044
108.4748595535856
106.35129382045952
112.2263734236363
106.66874481079738
116.87928723211712
130.5419408053182
115.09352004820528
108.43085519006488
99.6297146865368
92.91652151049244
83.64616823714262
107.55538458191654
114.028934882416
121.82282531297145
117.78376950991792
133.347247317031
57.88423935652551
120.58385138712416
115.47461004482956
109.45612087639456
92.14699491877842
110.88015991617476
92.7645001489992
133.63375961696246
57.88423935652551
118.65983898297765
119.66193800871709
111.77008652071396
144.58347610578087
119.20558237780747
114.47019224470344
122.7764770927691
121.97961354862996
104.98647724054088
107.78191153458695
119.75055351521996
122.77223986058917
110.0888830124039
112.811351865198
113.04418941868452
125.92204909531564
108.05245337508704
142.88785103453466
136.97288132766283
110.53267158559952
113.35058171561074
96.2410795442478
118.51054976885956
122.338942395638
93.1016192774638
96.87681621464075
122.00820189601382
101.8886950714448
120.0302045551314
123.180173026571
121.17878673936468
93.24714191718934
136.4070671508856
135.9875661032871
121.9057900809408
114.80790610202033
124.53320903315333
113.20429844126215
120.8171352491078
123.2831762531961
84.54815947407724
128.35648089624618
94.47060641147472
113.89747560952718
154.6149919198758
92.26524907409372
114.45992506498769
57.88423935652551
57.88423935652551
122.17228223451905
122.86420730872246
101.2157593030794
118.22797387709568
88.41948154629469
118.96926513698132
99.28924427491876
124.5001210063866
98.61268024972976
124.7664535748625
112.33660260515224
142.63540836557786
110.58573172151696
108.39542779529864
103.85451590373438
118.6333661891318
106.45573119749888
123.15060436119232
104.32988021181995
122.974779150865
136.09227355119208
94.4115854926882
138.02880958726377
108.88929520773831
113.45781131192729
92.05668245294956
97.64468854539054
111.95558004268548
111.44307154485448
90.7931450435276
137.76575171781715
116.88769410044642
114.1772261656132
107.93104988028946
118.47752240279932
94.69452878363614
112.27291518079652
103.50420316644504
94.67544421301204
101.6381026017538
128.02113944288206
132.93684984164798
111.32995971980512
92.00641125937132
113.57128536939835
153.43139149724738
122.784050004187
125.29796311161878
99.81312346726344
57.88423935652551
118.78169928344788
107.73323120457486
96.65006881614592
118.47820202358476
112.0050143956499
123.16463831221324
116.66832392405428
123.32537822809088
108.31290347649004
128.19285822796002
118.19056115668604
100.34221624333162
138.22724867280962
113.9503993386317
99.25351366885364
104.3329667956472
126.69699853094224
122.28082657681912
133.53236918289667
107.40184000282362
109.5714815298702
95.37390049789022
121.234587633315
115.66978642601411
109.46944135418268
82.22390060819802
117.22234684723324
112.01536067364404
110.72434623008532
83.67070915159988
93.1931638897685
129.8059453688184
82.49315790282927
105.3392555132043
96.12582174378134
105.86079302089593
127.58466672639986
112.84229353662391
115.1169354184373
128.07832894669588
118.86074297772204
138.0064262543064
109.76919195625338
91.26651497350755
108.32844521758592
57.88423935652551
105.64087886151178
114.76887078258864
120.4118520159312
139.44611974434014
124.25567220585664
120.91445163136235
115.1374775801244
129.42304819952545
116.17523800115724
138.1458031163242
127.93324866526774
122.4773127337396
119.9784222364901
118.217822597951
106.9865880392844
118.11387154720748
126.22298196541414
107.19612697713458
106.19792587838194
136.0375820446479
118.9363260172104
109.86244992359867
113.89262065618816
124.23185871844714
130.94449804534264
97.07121599383792
110.06518061400674
122.25069519357837
117.3324025395398
116.76431767370312
128.4460721377198
109.15253636620528
120.9830580221896
125.01014031234908
122.430828152838
106.4350848932954
108.96917408888272
96.69760560741553
111.74051533599425
109.4199829959379
100.02247627722664
87.5181603826931
109.77350034571468
119.85108493085583
116.52955498915016
110.86855978735696
127.89393785214436
121.46403071399968
123.6438106368999
113.78443056257926
132.58449435395414
121.2458423599551
135.53350552682542
122.89777533696854
100.6175721480914
139.4493375819932
71.65464861996455
94.33399151033814
116.69936457725792
130.07070793028487
126.99042460780346
109.88179523208971
108.01299865062276
106.92550107378732
126.36498437244316
119.7228888655614
108.49474119747089
126.0812210272737
121.24450892260442
136.8769136477446
141.09271596248556
107.6644040835382
91.9933474344224
104.87244583959873
103.69883933944496
103.01266922411524
126.28695190863522
123.84700508084924
118.80569597602934
111.49332650031296
101.38720020840869
116.6035862098391
111.77406292896642
103.17685187772544
111.28986232847166
132.25191435746967
111.08358229939878
92.26160036948022
101.85721377853646
115.99703227828417
113.49621041034877
113.90957132578475
121.5414558740555
57.88423935652551
120.32401326889271
115.06277979169089
111.5932666054699
103.64886969056926
126.95069810221538
123.4988233219136
107.87064621481407
57.88423935652551
107.80646469724404
124.3150189141183
109.62198919520394
121.88620851485028
112.22717508579406
57.88423935652551
90.41441417534976
117.7060417363836
120.8595913167401
137.26567727470388
125.58371610110716
110.71033969422614
113.15022383972637
121.19753142202028
105.73868851071498
115.51538657627503
108.96473102666124
123.88670526224378
120.61773995199952
122.66024043612838
110.32265953289134
110.57759110354831
132.84805841010464
124.50497075224403
110.62364801688445
125.49734115323918
100.64840412914
109.19758161578696
118.96421387267084
126.0342528772761
104.73158701090053
130.08198058048973
121.74982232550028
108.1390432443686
129.8839777441438
127.95604277129652
112.14941858105117
118.70159145587829
122.42649959330944
77.54194553087073
98.29936919701092
126.47287765176466
84.47049166529683
119.7843558277131
103.94701279747945
57.88423935652551
114.2234697059107
101.1342178594678
109.11482248617388
103.55081678278924
113.50001128904351
115.58024359115775
57.88423935652551
115.73160764833032
104.0264647957725
57.88423935652551
106.8813648422223
124.00913413790944
98.89478086963764
114.08220291311058
106.69305723692132
125.51052429793587
109.63222090786088
132.01649504950203
100.3790827082682
114.27049677555678
119.3301401492122
125.62868695179088
124.7394418117967
109.50793316001344
112.16049723612396
111.65749327775652
133.55613244537238
103.41145492398891
110.68880928854672
11.976239018890924
11.565452175873386
11.016560704849326
10.25683960401562
10.382788091536346
12.598300496114296
11.678049782822576
10.604591449367405
11.856385675229458
12.989218031942782
10.186711558764442
9.71650267591658
14.446458740412142
10.96865352892595
57.88423935652551
11.659128969648188
10.268461755448406
10.724290414026004
11.350036580306814
11.826443046826112
9.683563642736337
11.904860271583956
11.65724254551914
11.432808250824284
11.30908962940555
9.32250455670852
13.122400411025431
10.83486722598716
11.027490880220071
9.288112103523344
10.342818808645625
10.400818248587784
10.208625748454338
11.867641850988216
9.851602403850611
15.799818111788763
57.88423935652551
11.03055972520136
57.88423935652551
11.635820329729922
9.646269155014751
9.69424238197508
11.664552222137594
11.47424840760026
10.254925318811193
12.729719995192784
11.334898298214094
11.069173413964016
9.792365088622867
12.223591810092897
12.463194026066116
10.062284424887526
57.88423935652551
11.565147538580542
9.083273186436717
10.11811056969663
12.5360959337331
10.465282648837892
10.644263249706963
9.883175770931798
11.394834175948349
11.326956503059328
12.586659277159256
10.434222661942863
10.089725677982216
12.49342393786086
11.337235850990666
10.986815208965131
11.205327322812682
12.380380552088972
9.86128116694003
9.534385155384433
11.51725686661402
11.260004798850703
11.999628891309582
11.114818883767567
11.43386558952161
57.88423935652551
10.377887367806151
11.17543088378532
10.933183358482284
9.014171843577778
11.35926505798658
11.047598589001716
12.063349402734614
8.28378228845512
10.921845159128877
10.919335158980372
10.741932524353595
11.387552106776877
10.258916546178572
10.830547502940888
11.020786312570303
12.637538128443635
9.766234243757784
10.281534867550455
11.148186603159065
10.20691539180577
12.46518266995077
10.364826073959827
9.84260687008257
12.584648374502104
10.66352616968974
10.647609072093854
9.650120532757404
10.098513943695474
9.45752004917208
10.728412300486092
10.44420896480386
10.322160477931313
10.3883113646352
12.870716012469137
11.919901332922374
12.0900658451329
9.473762753262449
14.106990891776611
10.651413060748732
10.74598926429218
10.78176420934862
10.917311601528864
9.79970339628403
10.429135316501222
11.70635107354934
12.623773291245946
9.72274857845721
9.420663481665551
14.027243921844372
10.34291217618838
10.970320886659106
11.565149238152094
10.866746857839688
9.476416988563583
11.501474688411102
8.77410220529329
11.467322811620065
10.511448456290326
12.339940174296562
9.658778976730584
10.527242928287166
11.443105363500916
10.029412302071156
8.536633990796986
10.308606254081711
9.035875660592728
10.04039450374955
11.051003389474758
11.83338648542878
11.38466725058599
10.968995947346931
12.001322619745055
11.285170661691744
11.03215552648964
11.971092434071096
11.872422012021625
11.27472426970402
10.371273145783007
57.88423935652551
8.372005013545216
11.800239122460184
12.249761888960109
10.58001959761387
9.998442304429862
10.614598248846036
13.058791259290086
11.806726726641342
10.441008448152685
11.291132179530344
11.53974639636103
12.727371121193428
11.98426271897264
11.24769034136501
11.527199342606094
10.59211682734531
10.19019674266841
10.751877273022233
10.68837639703118
11.591504788539597
57.88423935652551
9.780834770637236
9.06226938632313
12.155212600219926
10.12281851573628
9.972683251591969
12.84921579167491
10.220057743618709
11.0017427872915
12.495070889094022
10.114263856610306
10.567477320958488
9.178908566152575
11.04525084098293
11.155926715997367
10.19839793042424
11.38635772338774
11.369942617024922
11.62910239899752
12.011127889737486
9.79031196851469
11.73739681229238
11.599780429287549
11.552016228192128
9.649998554140224
10.665921888852148
12.730576200657511
11.697225109170786
11.337731439168063
10.726024905500235
9.869466254031437
10.841438833850155
10.288800185383009
11.007866740303268
11.12484440549792
8.89836648305026
9.77444363268526
12.104508685297183
10.2012752772297
57.88423935652551
11.981556983329126
10.754747926535746
11.132099328070092
9.569823342330372
11.149194216027077
10.109361349578109
12.594031907573186
9.676768543128704
11.063018358325946
9.844674524572053
12.225057720947223
14.683505666279128
11.21494064118715
9.456474796287512
10.35502815561144
10.194374110671282
9.42527003936247
11.018605697641318
12.521934172963292
12.830745852074928
11.057301221507393
11.33559761547967
10.473814749615617
57.88423935652551
11.99081412346941
11.524999348320732
11.11673194997499
9.948423636145662
14.127536762949234
9.967468726243451
11.157030814820134
10.008485830089477
57.88423935652551
10.797199735660756
10.322098953559008
9.482025777611817
12.212623662295837
10.802046966051847
13.458871382474817
9.393488554945094
10.940987218656389
10.800004301500987
7.957911569991985
57.88423935652551
11.14530599458876
9.90613628513324
10.117349820466504
10.14504491733076
10.134978038239655
11.916625118729735
12.578399190130778
10.81280136799092
11.563301057236524
10.265062695277257
9.914030019689337
11.082892088284272
11.76642865360566
11.614978656158042
10.29118747093392
12.123662400452307
11.43506128758621
11.71269876470713
11.813671195553498
9.63798840085705
14.339673317136723
11.400563763863344
10.33134434116253
11.926870750034304
10.208678152800251
11.587428146474345
9.994598788726858
57.88423935652551
57.88423935652551
57.88423935652551
13.372799640230603
13.112027540829828
11.555524595765494
11.7838615271791
9.361516098542555
10.64309517676216
11.34262065371542
8.04562275398314
13.95354768634392
10.621449820634828
9.449368976878125
11.515774401300536
10.662588389869368
10.661919500066144
12.708069598377568
10.984156213062244
10.958058095035716
11.569833848502372
10.002531748228646
10.76111321117756
11.944406491292703
11.663439195824932
11.068894696095354
10.15045117926372
10.338298408144702
9.371068263246965
11.063680016192103
57.88423935652551
11.45954128859468
11.896274817392827
12.728900555322554
12.3723255665992
8.575812659084626
11.877709256216251
9.958926938936562
10.102147682210868
8.266586983283412
10.246058496484707
11.8156676176916
11.810861484633856
12.138085872050588
11.764782224381143
10.618035380073644
8.491855698890083
12.54716064735198
11.39015721501319
12.250407681953972
10.651712349884106
11.543939169471027
10.346301093972205
9.582553118704672
10.66475816101038
10.67771355211796
9.02727157666938
11.77627377959335
12.008456144624695
11.080409831333426
12.198020934312334
9.260154577573443
12.410327341796329
12.188210354742532
9.072089230349135
11.912468326959525
12.905709482435157
9.739660018790255
11.544740948318957
10.081614448463156
11.140178861008604
11.98825975671571
11.471062726146464
12.882835811708809
13.742754755305205
12.220195819301235
8.931600382421172
10.917167733184884
12.049448120635455
57.88423935652551
57.88423935652551
10.818121007462196
11.690966381389105
10.27682642938454
10.29867235876807
12.67056943984804
11.905887867774569
10.163205568926363
9.947481840242254
57.88423935652551
9.11011638199565
57.88423935652551
10.211228397597145
57.88423935652551
8.683959194926143
13.052899086114245
10.276630774040472
14.228894489407333
10.561600840065442
9.988408562284794
13.302706551769733
11.162257553620552
11.630069907160314
9.442193242087168
10.37379934878558
10.248106757039348
12.372798823014657
57.88423935652551
13.321425782698508
9.914710497532502
12.466074448550737
10.908026867356815
13.631255489401337
10.934225178952897
9.752885253161924
9.886610640029518
14.834288976671589
11.10915439013598
9.557396139775957
12.700139684227528
11.10879357158554
12.838516170811864
11.67996281014323
12.876029295338784
11.68721522424769
9.197969340794431
11.050506974742005
11.865303968035636
11.326371937632246
10.344990074559552
10.866659786461604
11.851435856604091
12.33921411434676
11.345563880569934
11.702392193589498
9.914180121362945
11.05088247772832
10.915891456630256
57.88423935652551
11.436647477702005
57.88423935652551
10.000151312469615
10.469169717482863
9.095202703131342
12.612932955489995
13.59444537550098
11.763440439540656
13.41225139878722
12.984597653908274
10.55580424635841
10.36456484411768
10.320565698802662
12.82858530130447
11.39413194490734
11.717573087064686
13.214209958871852
12.381463419328592
10.109228407154347
10.68132558167672
57.88423935652551
11.884700323778317
10.573771318834376
11.86890611202582
11.680370512025936
11.357078787162331
11.273704865454183
10.461310930635385
11.79273929586936
57.88423935652551
12.478994879302034
12.751060847084874
9.8812804097826
12.336861106841654
13.534433691988248
8.715450210157426
13.341760278743095
12.902966990698928
13.44590462373609
57.88423935652551
12.018263795896752
9.819615979999451
10.703799349393982
11.801441490622931
9.48375494681368
57.88423935652551
10.09089519477712
11.125336870302132
57.88423935652551
10.913275634770342
10.88815010972383
12.27446505717463
12.56181221880054
10.692490084216654
8.28702830968599
11.922773906459376
9.751874775949808
12.401535908446746
10.95931454374711
11.151471088388377
10.587925106217073
10.125265723266123
10.557273315824688
9.516375107238128
13.374548502610498
57.88423935652551
9.721384167448198
11.702535668416386
57.88423935652551
10.685424253813672
9.583368011630627
11.244524376631832
10.712959093626328
10.842268606202296
11.366903354946167
11.81916965792623
10.74778862345564
15.230874297931765
10.848981231976497
13.063595505075188
10.352877579400074
9.616069980034544
13.90609190177786
10.813079091565966
7.561199129885454
14.194185110539362
9.859528599251991
11.05578118191026
11.849710659345336
12.042884221218294
8.70531417222622
11.455373744504216
13.087719072769117
11.824620810205996
11.4254762114334
57.88423935652551

# 6) Afficher les valeurs uniques de la colonne Warranty

In [71]:
mower.warranty.unique()

array(['3ans', '3 ans.', '3_ans', '3 anss', '3ans.', '3 ans', '3_ans.',
       '3_anss', '3anss', '2 ans', '2 anss', '2anss', '2_ans', '2ans',
       '2_ans.', '2 ans.', '2_anss', '2ans.', '1 an', '1an', '1_an.',
       '1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'], dtype=object)

# 7) Traiter la colonne warranty afin d'uniformiser les valeurs

In [73]:
mower['warranty'].shape

(1399,)

In [79]:
mower['warranty'] = mower['warranty'].str[0].astype(int)

In [80]:
mower['warranty'].unique()

array([3, 2, 1])

# 8) Traiter la colonne warranty afin d'uniformiser les valeurs

In [117]:
mower['warranty'].unique()

array([3, 2, 1])

# 10) Transformer la colonne product_type en colonne numÃ©rique

In [122]:
mower=pd.read_csv('mower_market_snapshot.csv', delimiter=';')

In [123]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,essence,Low,1an.,0.001022,0.538969

In [124]:
mower['product_type']

0       auto-portee
1       auto-portee
2       auto-portee
3       auto-portee
4       auto-portee
           ...
1394        essence
1395        essence
1396        essence
1397        essence
1398        essence
Name: product_type, Length: 1399, dtype: object

In [126]:
mower['product_type'].replace(['auto-portee','essence','electrique'],['1','2','3'], inplace=True)

In [127]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,1,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,1,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,1,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,1,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,1,Medium,3ans.,0.007406,0.757614
...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,75.161102,11.498540481074583,2,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,11.380588736668567,2,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,unknown,2,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,9.794196773761458,2,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,10.696216086742934,2,Low,1an.,0.001022,0.538969

# 11) CrÃ©er 3 colonnes

In [145]:
mower["auto-portee"]=False
mower["essence"]=False
mower["electrique"]=False

In [146]:
mower.loc[mower["product_type"]==1,"auto-portee"]=True
mower.loc[mower["product_type"]==2,"essence"]=True
mower.loc[mower["product_type"]==3,"electrique"]=True

In [139]:
mower.loc[:,['auto-portee' , 'essence' ,'electrique']]

      auto-portee  essence  electrique
0               0        0           0
1               0        0           0
2               0        0           0
3               0        0           0
4               0        0           0
...           ...      ...         ...
1394            0        0           0
1395            0        0           0
1396            0        0           0
1397            0        0           0
1398            0        0           0

[1399 rows x 3 columns]

In [147]:
mower

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness,auto-portee,essence,electrique
0,10.492623,0.042528,18377,633.766584,501-++,195.03551928211797,1,Low,3ans,0.006360,0.650648,False,False,False
1,20.273730,0.037896,19363,731.576817,501-++,151.31809934886763,1,Low,3 ans.,0.006840,0.699792,False,False,False
2,20.190457,0.039111,19641,741.218202,501-++,178.13731921134948,1,Low,3_ans,0.006179,0.632129,False,False,False
3,27.220131,0.041303,18728,654.255635,501-++,162.82946157588628,1,Low,3 anss,0.007925,0.810730,False,False,False
4,16.370911,0.037938,18722,703.094527,501-++,141.48693796090603,1,Medium,3ans.,0.007406,0.757614,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,44.959895,0.234647,18451,63.662561,0-300,11.498540481074583,2,Medium,1 an,0.000973,0.513126,False,False,False
1395,59.356058,0.253694,18663,64.014543,0-300,11.380588736668567,2,Low,1ans,0.001038,0.547739,False,False,False
1396,67.865222,0.228935,19169,62.132035,501-++,unknown,2,Low,1an.,0.001243,0.655622,False,False,False
1397,66.855435,0.244948,18946,58.697122,0-300,9.794196773761458,2,Low,1 an,0.001644,0.867537,False,False,False
1398,54.712713,0.177143,19017,64.259212,0-300,10.696216086742934,2,Low,1an.,0.001022,0.538969,False,False,False

# 9 Traiter la colonne price

In [142]:
for length in mower.price:
    if length >= 0 and length <= 300:
        mower['price'].replace(length,"0-300", inplace=True)
    elif length > 300 and length <= 500:
        mower['price'].replace(length,"301-500", inplace=True)
    elif length > 501:
        mower['price'].replace(length,"501-++", inplace=True)

In [143]:
mower['price']

0       501-++
1       501-++
2       501-++
3       501-++
4       501-++
         ...
1394     0-300
1395     0-300
1396    501-++
1397     0-300
1398     0-300
Name: price, Length: 1399, dtype: object

# PARTIE 2

In [150]:
df1 = df.copy()

def create_colonne(df, columns, test1, emplace = 8):
    for col in columns:
        df.insert(emplace, col, 0)
    for col in df.loc[:,(columns)]:
        df[col] = df[test1].apply(lambda x : x == col).astype(int)
    return df

mower = create_colonne(df1, ["auto-portee", "essence", "electrique"], "product_type")
mower

IndexError: index 8 is out of bounds for axis 0 with size 1